#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
EVD="$ROOT/evidence"
SRC_FILE="$ROOT/scripts/sources.txt"
mkdir -p "$EVD"

if [[ ! -f "$SRC_FILE" ]]; then
  echo "Missing $SRC_FILE (copy from sources.example.txt)" >&2
  exit 1
fi

while IFS= read -r src; do
  [[ -z "$src" || "$src" =~ ^# ]] && continue
  base=$(basename "$src")
  scp "shsgpi:$src" "$EVD/$base"
  "$ROOT/scripts/sanitize.sh" "$EVD/$base"
done < "$SRC_FILE"

cat > "$EVD/INDEX.md" <<'MD'
# Evidence Index

Auto-generated by sync script from configured source list.
MD
for f in "$EVD"/*; do
  b=$(basename "$f")
  [[ "$b" == "INDEX.md" ]] && continue
  echo "- $b" >> "$EVD/INDEX.md"
done

echo "Synced and sanitized evidence into: $EVD"
